### ISSUE TITLE
No CORS headers

### ISSUE THREAD

**Issue by ronaldmansveld** [ciscou/cubecomps-mobile#3]
m.cubecomps.com exposes a json API through adding .json to the URL, however, because the respons headers miss the relevant CORS-headers, it is impossible to consume the API from a client side application.

For more information, see: https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS (among other resources)

**Comment by ciscou** [comment]
You're absolutely right. I'll give it a go.

I'll be glad to see what you're building when it's live :)

**Comment by ronaldmansveld** [comment]
Cool! If you need any help, give me a shout!

**Comment by ciscou** [comment]
Nah, I've done this before and it's super easy thanks to [rack-cors](https://github.com/cyu/rack-cors).

It should be working now!

Let me know if you need anything.

**Comment by ronaldmansveld** [comment]
Works indeed! Thank you!
