### ISSUE TITLE
Set up HTTPS

### ISSUE THREAD

**Issue by jonatanklosko** [ciscou/cubecomps-mobile#5]
I had to use [this hack](https://github.com/jonatanklosko/groupifier/commit/f44bee0d65a50a7ac0d3e316d44909bffae5e3ed) to prevent Chrome from blocking calls to your API from my website served over HTTPS. I would appreciate if you could set up HTTPS. [Let's Encrypt](https://letsencrypt.org/) offers free SSL certificates and I'd say the setup is straightforward, [example with Rails & Nginx](https://github.com/jonatanklosko/pss_surveys/blob/356a24437b16cb5166bc6002910b4a4c20d54eb4/deployment/setup_ssl.sh).

**Comment by ciscou** [comment]
Wow I missed your issue! Sorry! My github notifications are on fire these days.

I'll have a look. Thanks!

**Comment by ciscou** [comment]
@jonatanklosko all done! Thanks for reporting!
